/* ═══ SETS DATA ═══ */
const SET_A1_WORDS = [
  {it:'estate',    ar:'صيف',       startType:'vowel',    article:"l'", gender:'f'},
  {it:'amico',     ar:'صديق',      startType:'vowel',    article:"l'", gender:'m'},
  {it:'autobus',   ar:'أتوبيس',    startType:'vowel',    article:"l'", gender:'m'},
  {it:'amica',     ar:'صديقة',     startType:'vowel',    article:"l'", gender:'f'},
  {it:'libro',     ar:'كتاب',      startType:'consonant',article:'il', gender:'m'},
  {it:'treno',     ar:'قطار',      startType:'consonant',article:'il', gender:'m'},
  {it:'cinema',    ar:'سينما',     startType:'consonant',article:'il', gender:'m'},
  {it:'giornale',  ar:'جريدة',     startType:'consonant',article:'il', gender:'m'},
  {it:'pizza',     ar:'بيتزا',     startType:'consonant',article:'la', gender:'f'},
  {it:'cucina',    ar:'مطبخ',      startType:'consonant',article:'la', gender:'f'},
  {it:'porta',     ar:'باب',       startType:'consonant',article:'la', gender:'f'},
  {it:'camera',    ar:'غرفة',      startType:'consonant',article:'la', gender:'f'},
];

// ── Stage 2: اختيار الأداة من (il / lo / la / l') — 5 لكل حالة ──
const SET_A2_WORDS = [
  // l' — أي جنس + متحرك (5)
  {it:'invito',      ar:'دعوة',      startType:'vowel',    article:"l'", gender:'m'},
  {it:'ospedale',    ar:'مستشفى',    startType:'vowel',    article:"l'", gender:'m'},
  {it:'italiano',    ar:'الإيطالية', startType:'vowel',    article:"l'", gender:'m'},
  {it:'università',  ar:'جامعة',     startType:'vowel',    article:"l'", gender:'f'},
  {it:'ufficio',     ar:'مكتب',      startType:'vowel',    article:"l'", gender:'m'},
  // il — مذكر + ساكن عادي (5)
  {it:'caffè',       ar:'قهوة',      startType:'consonant',article:'il', gender:'m'},
  {it:'succo',       ar:'عصير',      startType:'consonant',article:'il', gender:'m'},
  {it:'tempo',       ar:'وقت',       startType:'consonant',article:'il', gender:'m'},
  {it:'quaderno',    ar:'كراسة',     startType:'consonant',article:'il', gender:'m'},
  {it:'cellulare',   ar:'موبايل',    startType:'consonant',article:'il', gender:'m'},
  // la — مؤنث + ساكن (5) — تشمل storia التي تبدأ بـ S+ساكن لكن مؤنثة
  {it:'palestra',    ar:'جيم',       startType:'consonant',article:'la', gender:'f'},
  {it:'bicicletta',  ar:'دراجة',     startType:'consonant',article:'la', gender:'f'},
  {it:'macchina',    ar:'سيارة',     startType:'consonant',article:'la', gender:'f'},
  {it:'storia',      ar:'تاريخ',     startType:'s_impure', article:'la', gender:'f'},
  {it:'colazione',   ar:'إفطار',     startType:'consonant',article:'la', gender:'f'},
  // lo — مذكر + S+ساكن (s_impure) (5)
  {it:'studente',    ar:'طالب',      startType:'s_impure', article:'lo', gender:'m'},
  {it:'sport',       ar:'رياضة',     startType:'s_impure', article:'lo', gender:'m'},
  {it:'stadio',      ar:'ملعب',      startType:'s_impure', article:'lo', gender:'m'},
  {it:'schermo',     ar:'شاشة',      startType:'s_impure', article:'lo', gender:'m'},
  {it:'spazio',      ar:'فضاء',      startType:'s_impure', article:'lo', gender:'m'},
  // lo — مذكر + Z (5)
  {it:'zaino',       ar:'حقيبة ظهر', startType:'z',        article:'lo', gender:'m'},
  {it:'zio',         ar:'عم / خال',  startType:'z',        article:'lo', gender:'m'},
  {it:'zero',        ar:'صفر',       startType:'z',        article:'lo', gender:'m'},
  {it:'zucchero',    ar:'سكر',       startType:'z',        article:'lo', gender:'m'},
  {it:'zoo',         ar:'حديقة حيوان',startType:'z',       article:'lo', gender:'m'},
  // كلمات العاقل (من الكتاب) — l'
  {it:'insegnante',  ar:'معلم/معلمة', startType:'vowel',   article:"l'", gender:'m'},
  {it:'architetto',  ar:'معماري',    startType:'vowel',    article:"l'", gender:'m'},
  // كلمات العاقل — il
  {it:'professore',  ar:'أستاذ',     startType:'consonant',article:'il', gender:'m'},
  {it:'ragazzo',     ar:'شاب/ولد',   startType:'consonant',article:'il', gender:'m'},
  {it:'cantante',    ar:'مغني',      startType:'consonant',article:'il', gender:'m'},
  // كلمات العاقل — la
  {it:'sorella',     ar:'أخت',       startType:'consonant',article:'la', gender:'f'},
  {it:'donna',       ar:'امرأة',     startType:'consonant',article:'la', gender:'f'},
  {it:'compagna',    ar:'زميلة',     startType:'consonant',article:'la', gender:'f'},
  {it:'studentessa', ar:'طالبة',     startType:'consonant',article:'la', gender:'f'},
  // كلمات الغير عاقل (من الكتاب) — l' (متحرك)
  {it:'albero',      ar:'شجرة',      startType:'vowel',    article:"l'", gender:'m'},
  {it:'esercizio',   ar:'تمرين',     startType:'vowel',    article:"l'", gender:'m'},
  {it:'aula',        ar:'فصل دراسي', startType:'vowel',    article:"l'", gender:'f'},
  {it:'arte',        ar:'فن',        startType:'vowel',    article:"l'", gender:'f'},
  {it:'immagine',    ar:'صورة',      startType:'vowel',    article:"l'", gender:'f'},
  {it:'astuccio',    ar:'مقلمة',     startType:'vowel',    article:"l'", gender:'m'},
  {it:'internet',    ar:'إنترنت',    startType:'vowel',    article:"l'", gender:'m'},
  // كلمات الغير عاقل — il (مذكر ساكن)
  {it:'pesce',       ar:'سمك',       startType:'consonant',article:'il', gender:'m'},
  {it:'ristorante',  ar:'مطعم',      startType:'consonant',article:'il', gender:'m'},
  {it:'cane',        ar:'كلب',       startType:'consonant',article:'il', gender:'m'},
  {it:'calcio',      ar:'كرة القدم', startType:'consonant',article:'il', gender:'m'},
  {it:'computer',    ar:'كمبيوتر',   startType:'consonant',article:'il', gender:'m'},
  {it:'post',        ar:'منشور',     startType:'consonant',article:'il', gender:'m'},
  {it:'blog',        ar:'مدونة',     startType:'consonant',article:'il', gender:'m'},
  {it:'piatto',      ar:'طبق',       startType:'consonant',article:'il', gender:'m'},
  {it:'palazzo',     ar:'قصر/مبنى',  startType:'consonant',article:'il', gender:'m'},
  {it:'panino',      ar:'ساندوتش',   startType:'consonant',article:'il', gender:'m'},
  // كلمات الغير عاقل — la (مؤنث ساكن — تشمل s+ساكن مؤنث)
  {it:'chiave',      ar:'مفتاح',     startType:'consonant',article:'la', gender:'f'},
  {it:'classe',      ar:'فصل/صف',    startType:'consonant',article:'la', gender:'f'},
  {it:'borsa',       ar:'حقيبة',     startType:'consonant',article:'la', gender:'f'},
  {it:'canzone',     ar:'أغنية',     startType:'consonant',article:'la', gender:'f'},
  {it:'festa',       ar:'حفلة/عيد',  startType:'consonant',article:'la', gender:'f'},
  {it:'lezione',     ar:'درس',       startType:'consonant',article:'la', gender:'f'},
  {it:'stazione',    ar:'محطة',      startType:'s_impure', article:'la', gender:'f'},
  {it:'materia',     ar:'مادة دراسية',startType:'consonant',article:'la', gender:'f'},
  {it:'pagina',      ar:'صفحة',      startType:'consonant',article:'la', gender:'f'},
  {it:'borsetta',    ar:'حقيبة صغيرة',startType:'consonant',article:'la', gender:'f'},
  {it:'zona',        ar:'منطقة',     startType:'consonant',article:'la', gender:'f'},
  // كلمات الغير عاقل — lo (مذكر s+ساكن)
  {it:'stivale',     ar:'حذاء طويل', startType:'s_impure', article:'lo', gender:'m'},
  {it:'studio',      ar:'مكتب/استوديو',startType:'s_impure',article:'lo', gender:'m'},
  {it:'sms',         ar:'رسالة نصية',startType:'s_impure', article:'lo', gender:'m'},
];

// ── Stage 3: كتابة الأداة من الذاكرة — 5 لكل حالة، كلمات جديدة أصعب ──
const SET_A3_WORDS = [
  // l' (5)
  {it:'appartamento',ar:'شقة',       startType:'vowel',    article:"l'", gender:'m'},
  {it:'ora',         ar:'ساعة',      startType:'vowel',    article:"l'", gender:'f'},
  {it:'inverno',     ar:'شتاء',      startType:'vowel',    article:"l'", gender:'m'},
  {it:'isola',       ar:'جزيرة',     startType:'vowel',    article:"l'", gender:'f'},
  {it:'esame',       ar:'امتحان',    startType:'vowel',    article:"l'", gender:'m'},
  // il (5)
  {it:'telefono',    ar:'هاتف',      startType:'consonant',article:'il', gender:'m'},
  {it:'tè',          ar:'شاي',       startType:'consonant',article:'il', gender:'m'},
  {it:'film',        ar:'فيلم',      startType:'consonant',article:'il', gender:'m'},
  {it:'messaggio',   ar:'رسالة',     startType:'consonant',article:'il', gender:'m'},
  {it:'regalo',      ar:'هدية',      startType:'consonant',article:'il', gender:'m'},
  // la (5) — تشمل stazione التي تبدأ بـ S+ساكن لكن مؤنثة
  {it:'verità',      ar:'حقيقة',     startType:'consonant',article:'la', gender:'f'},
  {it:'spesa',       ar:'تسوق',      startType:'s_impure', article:'la', gender:'f'},
  {it:'voce',        ar:'صوت',       startType:'consonant',article:'la', gender:'f'},
  {it:'lingua',      ar:'لغة',       startType:'consonant',article:'la', gender:'f'},
  {it:'famiglia',    ar:'عائلة',     startType:'consonant',article:'la', gender:'f'},
  // lo — S+ساكن (5) — نفس المرحلة 2 لكن الآن الطالب يكتب بدون خيارات
  {it:'studente',    ar:'طالب',      startType:'s_impure', article:'lo', gender:'m'},
  {it:'sport',       ar:'رياضة',     startType:'s_impure', article:'lo', gender:'m'},
  {it:'stadio',      ar:'ملعب',      startType:'s_impure', article:'lo', gender:'m'},
  {it:'schermo',     ar:'شاشة',      startType:'s_impure', article:'lo', gender:'m'},
  {it:'spazio',      ar:'فضاء',      startType:'s_impure', article:'lo', gender:'m'},
  // lo — Z (5)
  {it:'zaino',       ar:'حقيبة ظهر', startType:'z',        article:'lo', gender:'m'},
  {it:'zio',         ar:'عم / خال',  startType:'z',        article:'lo', gender:'m'},
  {it:'zero',        ar:'صفر',       startType:'z',        article:'lo', gender:'m'},
  {it:'zucchero',    ar:'سكر',       startType:'z',        article:'lo', gender:'m'},
  {it:'zoo',         ar:'حديقة حيوان',startType:'z',       article:'lo', gender:'m'},
  // كلمات العاقل (من الكتاب) — كتابة بدون خيارات
  {it:'insegnante',  ar:'معلم/معلمة', startType:'vowel',   article:"l'", gender:'m'},
  {it:'architetto',  ar:'معماري',    startType:'vowel',    article:"l'", gender:'m'},
  {it:'professore',  ar:'أستاذ',     startType:'consonant',article:'il', gender:'m'},
  {it:'ragazzo',     ar:'شاب/ولد',   startType:'consonant',article:'il', gender:'m'},
  {it:'cantante',    ar:'مغني',      startType:'consonant',article:'il', gender:'m'},
  {it:'sorella',     ar:'أخت',       startType:'consonant',article:'la', gender:'f'},
  {it:'donna',       ar:'امرأة',     startType:'consonant',article:'la', gender:'f'},
  {it:'compagna',    ar:'زميلة',     startType:'consonant',article:'la', gender:'f'},
  {it:'studentessa', ar:'طالبة',     startType:'consonant',article:'la', gender:'f'},
  // كلمات الغير عاقل (من الكتاب) — كتابة بدون خيارات
  {it:'albero',      ar:'شجرة',      startType:'vowel',    article:"l'", gender:'m'},
  {it:'esercizio',   ar:'تمرين',     startType:'vowel',    article:"l'", gender:'m'},
  {it:'aula',        ar:'فصل دراسي', startType:'vowel',    article:"l'", gender:'f'},
  {it:'arte',        ar:'فن',        startType:'vowel',    article:"l'", gender:'f'},
  {it:'immagine',    ar:'صورة',      startType:'vowel',    article:"l'", gender:'f'},
  {it:'astuccio',    ar:'مقلمة',     startType:'vowel',    article:"l'", gender:'m'},
  {it:'pesce',       ar:'سمك',       startType:'consonant',article:'il', gender:'m'},
  {it:'ristorante',  ar:'مطعم',      startType:'consonant',article:'il', gender:'m'},
  {it:'cane',        ar:'كلب',       startType:'consonant',article:'il', gender:'m'},
  {it:'calcio',      ar:'كرة القدم', startType:'consonant',article:'il', gender:'m'},
  {it:'piatto',      ar:'طبق',       startType:'consonant',article:'il', gender:'m'},
  {it:'panino',      ar:'ساندوتش',   startType:'consonant',article:'il', gender:'m'},
  {it:'chiave',      ar:'مفتاح',     startType:'consonant',article:'la', gender:'f'},
  {it:'classe',      ar:'فصل/صف',    startType:'consonant',article:'la', gender:'f'},
  {it:'borsa',       ar:'حقيبة',     startType:'consonant',article:'la', gender:'f'},
  {it:'canzone',     ar:'أغنية',     startType:'consonant',article:'la', gender:'f'},
  {it:'festa',       ar:'حفلة/عيد',  startType:'consonant',article:'la', gender:'f'},
  {it:'lezione',     ar:'درس',       startType:'consonant',article:'la', gender:'f'},
  {it:'stazione',    ar:'محطة',      startType:'s_impure', article:'la', gender:'f'},
  {it:'materia',     ar:'مادة دراسية',startType:'consonant',article:'la', gender:'f'},
  {it:'stivale',     ar:'حذاء طويل', startType:'s_impure', article:'lo', gender:'m'},
  {it:'studio',      ar:'مكتب/استوديو',startType:'s_impure',article:'lo', gender:'m'},
];

// ── أداة النكرة: un · uno · una · un' ──
// القاعدة: un (مذكر ساكن/متحرك) | uno (مذكر s+ساكن أو z) | una (مؤنث ساكن) | un' (مؤنث متحرك)
const SET_A_INDEF_WORDS = [
  // un — مذكر (ساكن عادي)
  {it:'ragazzo',     ar:'شاب/ولد',   startType:'consonant',unArt:'un',   gender:'m'},
  {it:'professore',  ar:'أستاذ',     startType:'consonant',unArt:'un',   gender:'m'},
  {it:'cantante',    ar:'مغني',      startType:'consonant',unArt:'un',   gender:'m'},
  {it:'libro',       ar:'كتاب',      startType:'consonant',unArt:'un',   gender:'m'},
  {it:'treno',       ar:'قطار',      startType:'consonant',unArt:'un',   gender:'m'},
  // un — مذكر (متحرك) — لا apostrophe للمذكر
  {it:'amico',       ar:'صديق',      startType:'vowel',    unArt:'un',   gender:'m'},
  {it:'architetto',  ar:'معماري',    startType:'vowel',    unArt:'un',   gender:'m'},
  {it:'insegnante',  ar:'معلم',      startType:'vowel',    unArt:'un',   gender:'m'},
  // uno — مذكر (s+ساكن أو z)
  {it:'studente',    ar:'طالب',      startType:'s_impure', unArt:'uno',  gender:'m'},
  {it:'sport',       ar:'رياضة',     startType:'s_impure', unArt:'uno',  gender:'m'},
  {it:'zaino',       ar:'حقيبة ظهر', startType:'z',        unArt:'uno',  gender:'m'},
  {it:'zio',         ar:'عم / خال',  startType:'z',        unArt:'uno',  gender:'m'},
  // una — مؤنث (ساكن)
  {it:'sorella',     ar:'أخت',       startType:'consonant',unArt:'una',  gender:'f'},
  {it:'donna',       ar:'امرأة',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'compagna',    ar:'زميلة',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'studentessa', ar:'طالبة',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'pizza',       ar:'بيتزا',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'macchina',    ar:'سيارة',     startType:'consonant',unArt:'una',  gender:'f'},
  // un' — مؤنث (متحرك) — apostrophe للمؤنث فقط
  {it:'amica',       ar:'صديقة',     startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'insegnante',  ar:'معلمة',     startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'università',  ar:'جامعة',     startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'ora',         ar:'ساعة',      startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'isola',       ar:'جزيرة',     startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'aula',        ar:'فصل دراسي', startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'immagine',    ar:'صورة',      startType:'vowel',    unArt:"un'",  gender:'f'},
  {it:'arte',        ar:'فن',        startType:'vowel',    unArt:"un'",  gender:'f'},
  // un — مذكر (متحرك) — لا apostrophe للمذكر أبداً
  {it:'albero',      ar:'شجرة',      startType:'vowel',    unArt:'un',   gender:'m'},
  {it:'esercizio',   ar:'تمرين',     startType:'vowel',    unArt:'un',   gender:'m'},
  {it:'astuccio',    ar:'مقلمة',     startType:'vowel',    unArt:'un',   gender:'m'},
  // un — مذكر (ساكن عادي) — الغير عاقل
  {it:'cane',        ar:'كلب',       startType:'consonant',unArt:'un',   gender:'m'},
  {it:'ristorante',  ar:'مطعم',      startType:'consonant',unArt:'un',   gender:'m'},
  {it:'pesce',       ar:'سمك',       startType:'consonant',unArt:'un',   gender:'m'},
  {it:'piatto',      ar:'طبق',       startType:'consonant',unArt:'un',   gender:'m'},
  {it:'panino',      ar:'ساندوتش',   startType:'consonant',unArt:'un',   gender:'m'},
  {it:'blog',        ar:'مدونة',     startType:'consonant',unArt:'un',   gender:'m'},
  {it:'computer',    ar:'كمبيوتر',   startType:'consonant',unArt:'un',   gender:'m'},
  {it:'calcio',      ar:'كرة القدم', startType:'consonant',unArt:'un',   gender:'m'},
  // uno — مذكر (s+ساكن) — الغير عاقل
  {it:'stivale',     ar:'حذاء طويل', startType:'s_impure', unArt:'uno',  gender:'m'},
  {it:'studio',      ar:'مكتب/استوديو',startType:'s_impure',unArt:'uno',gender:'m'},
  {it:'sms',         ar:'رسالة نصية',startType:'s_impure', unArt:'uno',  gender:'m'},
  // una — مؤنث (ساكن) — الغير عاقل
  {it:'chiave',      ar:'مفتاح',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'classe',      ar:'فصل/صف',    startType:'consonant',unArt:'una',  gender:'f'},
  {it:'borsa',       ar:'حقيبة',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'canzone',     ar:'أغنية',     startType:'consonant',unArt:'una',  gender:'f'},
  {it:'festa',       ar:'حفلة/عيد',  startType:'consonant',unArt:'una',  gender:'f'},
  {it:'lezione',     ar:'درس',       startType:'consonant',unArt:'una',  gender:'f'},
  {it:'stazione',    ar:'محطة',      startType:'s_impure', unArt:'una',  gender:'f'},
  {it:'materia',     ar:'مادة دراسية',startType:'consonant',unArt:'una', gender:'f'},
  {it:'pagina',      ar:'صفحة',      startType:'consonant',unArt:'una',  gender:'f'},
  {it:'zona',        ar:'منطقة',     startType:'consonant',unArt:'una',  gender:'f'},
];
