const SET_G_CHUNKS = [
  // ── IL (مذكر مفرد ساكن عادي) ──
  {it:'AL',    ar:'a + il',    note:'مذكر مفرد يبدأ بساكن عادي — a + il = AL',
   decomp:'a + il', prep:'a', art:'il',
   examples:[{it:'al bar',ar:'في الكافيه'},{it:'al lavoro',ar:'في العمل'},{it:'al parco',ar:'في الحديقة'},{it:'al mercato',ar:'في السوق'}]},
  {it:'DAL',   ar:'da + il',   note:'مذكر مفرد ساكن — da + il = DAL',
   decomp:'da + il', prep:'da', art:'il',
   examples:[{it:'dal dottore',ar:'من عند الطبيب'},{it:'dal lavoro',ar:'من العمل'},{it:'dal treno',ar:'من القطار'},{it:'dal bar',ar:'من الكافيه'}]},
  {it:'NEL',   ar:'in + il',   note:'مذكر مفرد ساكن — in + il = NEL',
   decomp:'in + il', prep:'in', art:'il',
   examples:[{it:'nel salotto',ar:'في الصالون'},{it:'nel parco',ar:'في الحديقة'},{it:'nel pomeriggio',ar:'بعد الظهر'},{it:'nel libro',ar:'في الكتاب'}]},
  {it:'SUL',   ar:'su + il',   note:'مذكر مفرد ساكن — su + il = SUL',
   decomp:'su + il', prep:'su', art:'il',
   examples:[{it:'sul tavolo',ar:'على الطاولة'},{it:'sul cellulare',ar:'على الموبايل'},{it:'sul web',ar:'على الإنترنت'},{it:'sul treno',ar:'على القطار'}]},
  {it:'DEL',   ar:'di + il',   note:'مذكر مفرد ساكن — di + il = DEL',
   decomp:'di + il', prep:'di', art:'il',
   examples:[{it:'del pane',ar:'من الخبز'},{it:'del tempo',ar:'من الوقت'},{it:'del vino',ar:'من النبيذ'},{it:'del caffè',ar:'من القهوة'}]},
  // ── LA (مؤنث مفرد ساكن) ──
  {it:'ALLA',  ar:'a + la',    note:'مؤنث مفرد يبدأ بساكن — a + la = ALLA',
   decomp:'a + la', prep:'a', art:'la',
   examples:[{it:'alla stazione',ar:'إلى المحطة'},{it:'alla festa',ar:'في الحفل'},{it:'alla fine',ar:'في النهاية'},{it:'alla porta',ar:'عند الباب'}]},
  {it:'DALLA', ar:'da + la',   note:'مؤنث مفرد ساكن — da + la = DALLA',
   decomp:'da + la', prep:'da', art:'la',
   examples:[{it:'dalla porta',ar:'من الباب'},{it:'dalla stazione',ar:'من المحطة'},{it:'dalla finestra',ar:'من النافذة'},{it:'dalla mamma',ar:'من عند الأم'}]},
  {it:'NELLA', ar:'in + la',   note:'مؤنث مفرد ساكن — in + la = NELLA',
   decomp:'in + la', prep:'in', art:'la',
   examples:[{it:'nella stanza',ar:'في الغرفة'},{it:'nella cucina',ar:'في المطبخ'},{it:'nella borsa',ar:'في الحقيبة'}]},
  {it:'SULLA', ar:'su + la',   note:'مؤنث مفرد ساكن — su + la = SULLA',
   decomp:'su + la', prep:'su', art:'la',
   examples:[{it:'sulla sedia',ar:'على الكرسي'},{it:'sulla strada',ar:'على الطريق'},{it:'sulla carta',ar:'على الورقة'},{it:'sulla tavola',ar:'على المائدة'}]},
  {it:'DELLA', ar:'di + la',   note:'مؤنث مفرد ساكن — di + la = DELLA',
   decomp:'di + la', prep:'di', art:'la',
   examples:[{it:'della casa',ar:'من/لـ المنزل'},{it:'della pizza',ar:'من/لـ البيتزا'},{it:'della città',ar:'من/لـ المدينة'},{it:'della famiglia',ar:'من/لـ العائلة'}]},
  // ── L' (مفرد متحرك) ──
  {it:"ALL'",  ar:"a + l'",    note:"مفرد يبدأ بمتحرك أي جنس — a + l' = ALL'",
   decomp:"a + l'", prep:'a', art:"l'",
   examples:[{it:"all'ospedale",ar:"إلى المستشفى"},{it:"all'università",ar:"إلى الجامعة"},{it:"all'aeroporto",ar:"إلى المطار"},{it:"all'inizio",ar:"في البداية"}]},
  {it:"DALL'", ar:"da + l'",   note:"مفرد متحرك أي جنس — da + l' = DALL'",
   decomp:"da + l'", prep:'da', art:"l'",
   examples:[{it:"dall'amico",ar:"من الصديق"},{it:"dall'ospedale",ar:"من المستشفى"},{it:"dall'aeroporto",ar:"من المطار"},{it:"dall'inizio",ar:"من البداية"}]},
  {it:"NELL'", ar:"in + l'",   note:"مفرد متحرك أي جنس — in + l' = NELL'",
   decomp:"in + l'", prep:'in', art:"l'",
   examples:[{it:"nell'appartamento",ar:"في الشقة"},{it:"nell'aria",ar:"في الهواء"},{it:"nell'ospedale",ar:"في المستشفى"},{it:"nell'università",ar:"في الجامعة"}]},
  {it:"SULL'", ar:"su + l'",   note:"مفرد متحرك أي جنس — su + l' = SULL'",
   decomp:"su + l'", prep:'su', art:"l'",
   examples:[{it:"sull'autobus",ar:"على الأتوبيس"},{it:"sull'albero",ar:"على الشجرة"},{it:"sull'aereo",ar:"على الطائرة"},{it:"sull'isola",ar:"على الجزيرة"}]},
  {it:"DELL'", ar:"di + l'",   note:"مفرد متحرك أي جنس — di + l' = DELL'",
   decomp:"di + l'", prep:'di', art:"l'",
   examples:[{it:"dell'amico",ar:"لـ/من الصديق"},{it:"dell'estate",ar:"من/لـ الصيف"},{it:"dell'acqua",ar:"من الماء"},{it:"dell'ospedale",ar:"من المستشفى"}]},
  // ── LO (مذكر مفرد s+ساكن أو z) ──
  {it:'ALLO',  ar:'a + lo',    note:'مذكر مفرد يبدأ بـ s+ساكن أو z — a + lo = ALLO',
   decomp:'a + lo', prep:'a', art:'lo',
   examples:[{it:'allo stadio',ar:'إلى الملعب'},{it:'allo specchio',ar:'في المرآة'},{it:'allo studente',ar:'للطالب'},{it:'allo zaino',ar:'للحقيبة'}]},
  {it:'DALLO', ar:'da + lo',   note:'مذكر مفرد s+ساكن أو z — da + lo = DALLO',
   decomp:'da + lo', prep:'da', art:'lo',
   examples:[{it:'dallo stadio',ar:'من الملعب'},{it:'dallo specchio',ar:'من المرآة'},{it:'dallo studente',ar:'من الطالب'},{it:'dallo zaino',ar:'من الحقيبة'}]},
  {it:'NELLO', ar:'in + lo',   note:'مذكر مفرد s+ساكن أو z — in + lo = NELLO',
   decomp:'in + lo', prep:'in', art:'lo',
   examples:[{it:'nello stadio',ar:'في الملعب'},{it:'nello specchio',ar:'في المرآة'},{it:'nello zaino',ar:'في الحقيبة'},{it:'nello stesso posto',ar:'في نفس المكان'}]},
  {it:'SULLO', ar:'su + lo',   note:'مذكر مفرد s+ساكن أو z — su + lo = SULLO',
   decomp:'su + lo', prep:'su', art:'lo',
   examples:[{it:'sullo schermo',ar:'على الشاشة'},{it:'sullo zaino',ar:'على الحقيبة'},{it:'sullo stadio',ar:'فوق الملعب'},{it:'sullo stesso tavolo',ar:'على نفس الطاولة'}]},
  {it:'DELLO', ar:'di + lo',   note:'مذكر مفرد s+ساكن أو z — di + lo = DELLO',
   decomp:'di + lo', prep:'di', art:'lo',
   examples:[{it:'dello studente',ar:'لـ/من الطالب'},{it:'dello zaino',ar:'لـ/من الحقيبة'},{it:'dello stadio',ar:'لـ/من الملعب'},{it:'dello specchio',ar:'لـ/من المرآة'}]},
  // ── الجمع المذكر عادي ──
  {it:'AI',    ar:'a + i',     note:'جمع مذكر عادي — a + i = AI',
   decomp:'a + i', prep:'a', art:'i',
   examples:[{it:'ai bambini',ar:'للأطفال'},{it:'ai ragazzi',ar:'للشباب'},{it:'ai negozi',ar:'للمحلات'},{it:'ai miei amici',ar:'لأصدقائي'}]},
  {it:'DAI',   ar:'da + i',    note:'جمع مذكر عادي — da + i = DAI',
   decomp:'da + i', prep:'da', art:'i',
   examples:[{it:'dai ragazzi',ar:'من الشباب'},{it:'dai miei amici',ar:'من أصدقائي'},{it:'dai bambini',ar:'من الأطفال'},{it:'dai negozi',ar:'من المحلات'}]},
  {it:'NEI',   ar:'in + i',    note:'جمع مذكر عادي — in + i = NEI',
   decomp:'in + i', prep:'in', art:'i',
   examples:[{it:'nei parchi',ar:'في الحدائق'},{it:'nei libri',ar:'في الكتب'},{it:'nei negozi',ar:'في المحلات'},{it:'nei paesi',ar:'في البلدان'}]},
  {it:'SUI',   ar:'su + i',    note:'جمع مذكر عادي — su + i = SUI',
   decomp:'su + i', prep:'su', art:'i',
   examples:[{it:'sui libri',ar:'على الكتب'},{it:'sui tavoli',ar:'على الطاولات'},{it:'sui giornali',ar:'في الجرائد'},{it:'sui muri',ar:'على الجدران'}]},
  {it:'DEI',   ar:'di + i',    note:'جمع مذكر عادي — di + i = DEI',
   decomp:'di + i', prep:'di', art:'i',
   examples:[{it:'dei libri',ar:'من/بعض الكتب'},{it:'dei ragazzi',ar:'من/بعض الشباب'},{it:'dei problemi',ar:'من المشاكل'},{it:'dei soldi',ar:'من الأموال'}]},
  // ── الجمع المذكر متحرك/s+ساكن ──
  {it:'AGLI',  ar:'a + gli',   note:'جمع مذكر متحرك أو s+ساكن — a + gli = AGLI',
   decomp:'a + gli', prep:'a', art:'gli',
   examples:[{it:'agli amici',ar:'للأصدقاء'},{it:'agli studenti',ar:'للطلاب'},{it:'agli alberi',ar:'للأشجار'},{it:'agli esami',ar:'للامتحانات'}]},
  {it:'DAGLI', ar:'da + gli',  note:'جمع مذكر متحرك أو s+ساكن — da + gli = DAGLI',
   decomp:'da + gli', prep:'da', art:'gli',
   examples:[{it:'dagli amici',ar:'من الأصدقاء'},{it:'dagli studenti',ar:'من الطلاب'},{it:'dagli alberi',ar:'من الأشجار'},{it:'dagli esami',ar:'من الامتحانات'}]},
  {it:'NEGLI', ar:'in + gli',  note:'جمع مذكر متحرك أو s+ساكن — in + gli = NEGLI',
   decomp:'in + gli', prep:'in', art:'gli',
   examples:[{it:'negli appartamenti',ar:'في الشقق'},{it:'negli stadi',ar:'في الملاعب'},{it:'negli esami',ar:'في الامتحانات'},{it:'negli anni',ar:'في السنوات'}]},
  {it:'SUGLI', ar:'su + gli',  note:'جمع مذكر متحرك أو s+ساكن — su + gli = SUGLI',
   decomp:'su + gli', prep:'su', art:'gli',
   examples:[{it:'sugli alberi',ar:'على الأشجار'},{it:'sugli specchi',ar:'على المرايا'},{it:'sugli scaffali',ar:'على الرفوف'},{it:'sugli studenti',ar:'عن الطلاب'}]},
  {it:'DEGLI', ar:'di + gli',  note:'جمع مذكر متحرك أو s+ساكن — di + gli = DEGLI',
   decomp:'di + gli', prep:'di', art:'gli',
   examples:[{it:'degli amici',ar:'من/بعض الأصدقاء'},{it:'degli studenti',ar:'من/بعض الطلاب'},{it:'degli alberi',ar:'من الأشجار'},{it:'degli esercizi',ar:'من التمارين'}]},
  // ── الجمع المؤنث ──
  {it:'ALLE',  ar:'a + le',    note:'جمع مؤنث دائماً — a + le = ALLE',
   decomp:'a + le', prep:'a', art:'le',
   examples:[{it:'alle ragazze',ar:'للبنات'},{it:'alle feste',ar:'للحفلات'},{it:'alle otto',ar:'الساعة الثامنة'},{it:'alle scuole',ar:'للمدارس'}]},
  {it:'DALLE', ar:'da + le',   note:'جمع مؤنث — da + le = DALLE',
   decomp:'da + le', prep:'da', art:'le',
   examples:[{it:'dalle ragazze',ar:'من البنات'},{it:'dalle case',ar:'من المنازل'},{it:'dalle otto',ar:'من الساعة الثامنة'},{it:'dalle strade',ar:'من الشوارع'}]},
  {it:'NELLE', ar:'in + le',   note:'جمع مؤنث — in + le = NELLE',
   decomp:'in + le', prep:'in', art:'le',
   examples:[{it:'nelle case',ar:'في المنازل'},{it:'nelle strade',ar:'في الشوارع'},{it:'nelle scuole',ar:'في المدارس'},{it:'nelle città',ar:'في المدن'}]},
  {it:'SULLE', ar:'su + le',   note:'جمع مؤنث — su + le = SULLE',
   decomp:'su + le', prep:'su', art:'le',
   examples:[{it:'sulle sedie',ar:'على الكراسي'},{it:'sulle scale',ar:'على السلالم'},{it:'sulle mappe',ar:'على الخرائط'},{it:'sulle strade',ar:'على الطرق'}]},
  {it:'DELLE', ar:'di + le',   note:'جمع مؤنث — di + le = DELLE',
   decomp:'di + le', prep:'di', art:'le',
   examples:[{it:'delle ragazze',ar:'من/بعض البنات'},{it:'delle case',ar:'من/بعض المنازل'},{it:'delle città',ar:'من/بعض المدن'},{it:'delle strade',ar:'من الشوارع'}]},
];
