const SET_C_WORDS = [
  {it:'libro',        ar:'كتاب',      article:'il',  hint:'مذكر + ساكن عادي'},
  {it:'studente',     ar:'طالب',      article:'lo',  hint:'مذكر + S وساكن'},
  {it:'zaino',        ar:'حقيبة ظهر', article:'lo',  hint:'مذكر + Z'},
  {it:'amico',        ar:'صديق',      article:"l'",  hint:'مذكر + حرف متحرك A'},
  {it:'ospedale',     ar:'مستشفى',    article:"l'",  hint:'مذكر + حرف متحرك O'},
  {it:'porta',        ar:'باب',       article:'la',  hint:'مؤنث + ساكن'},
  {it:'macchina',     ar:'سيارة',     article:'la',  hint:'مؤنث + ساكن'},
  {it:'amica',        ar:'صديقة',     article:"l'",  hint:'مؤنث + حرف متحرك A'},
  {it:'università',   ar:'جامعة',     article:"l'",  hint:'مؤنث + حرف متحرك U'},
  {it:'estate',      ar:'صيف',                 article:"l'",  hint:'مؤنث + متحرك E'},
  {it:'autobus',     ar:'أتوبيس',              article:"l'",  hint:'مذكر + متحرك A'},
  {it:'cinema',      ar:'سينما',               article:"il",  hint:'مذكر استثناء -A'},
  {it:'giornale',    ar:'جريدة',               article:"il",  hint:'مذكر + ساكن -E'},
  {it:'pizza',       ar:'بيتزا',               article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'cucina',      ar:'مطبخ',                article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'camera',      ar:'غرفة',                article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'invito',      ar:'دعوة',                article:"l'",  hint:'مذكر + متحرك I'},
  {it:'italiano',    ar:'إيطالي',              article:"l'",  hint:'مذكر + متحرك I'},
  {it:'ufficio',     ar:'مكتب',                article:"l'",  hint:'مذكر + متحرك U'},
  {it:'succo',       ar:'عصير',                article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'tempo',       ar:'وقت / طقس',           article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'quaderno',    ar:'كراسة',               article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'cellulare',   ar:'موبايل',              article:"il",  hint:'مذكر + ساكن -E'},
  {it:'palestra',    ar:'صالة رياضية',         article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'bicicletta',  ar:'دراجة هوائية',        article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'storia',      ar:'تاريخ / قصة',         article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'colazione',   ar:'إفطار',               article:"la",  hint:'مؤنث + ساكن -E'},
  {it:'sport',       ar:'رياضة',               article:"lo",  hint:'مذكر + S+ساكن'},
  {it:'stadio',      ar:'ملعب',                article:"lo",  hint:'مذكر + S+ساكن'},
  {it:'schermo',     ar:'شاشة',                article:"lo",  hint:'مذكر + S+ساكن'},
  {it:'spazio',      ar:'فضاء / مساحة',        article:"lo",  hint:'مذكر + S+ساكن'},
  {it:'zio',         ar:'عم / خال',            article:"lo",  hint:'مذكر + Z'},
  {it:'zero',        ar:'صفر',                 article:"lo",  hint:'مذكر + Z'},
  {it:'zucchero',    ar:'سكر',                 article:"lo",  hint:'مذكر + Z'},
  {it:'zoo',         ar:'حديقة حيوان',         article:"lo",  hint:'مذكر + Z'},
  {it:'appartamento',ar:'شقة',                 article:"l'",  hint:'مذكر + متحرك A'},
  {it:'ora',         ar:'ساعة / الآن',         article:"l'",  hint:'مؤنث + متحرك O'},
  {it:'inverno',     ar:'شتاء',                article:"l'",  hint:'مذكر + متحرك I'},
  {it:'isola',       ar:'جزيرة',               article:"l'",  hint:'مؤنث + متحرك I'},
  {it:'esame',       ar:'امتحان',              article:"l'",  hint:'مذكر + متحرك E'},
  {it:'telefono',    ar:'هاتف',                article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'tè',          ar:'شاي',                 article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'film',        ar:'فيلم',                article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'messaggio',   ar:'رسالة',               article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'regalo',      ar:'هدية',                article:"il",  hint:'مذكر + ساكن عادي'},
  {it:'verità',      ar:'حقيقة',               article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'spesa',       ar:'تسوق / مشتريات',      article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'voce',        ar:'صوت',                 article:"la",  hint:'مؤنث + ساكن -E'},
  {it:'lingua',      ar:'لغة / لسان',          article:"la",  hint:'مؤنث + ساكن عادي'},
  {it:'famiglia',    ar:'عائلة',               article:"la",  hint:'مؤنث + ساكن عادي'}
];
