const SET_B_WORDS = [
  {it:'libro',     ar:'كتاب',      gender:'m', ending:'o', isException:false},
  {it:'treno',     ar:'قطار',      gender:'m', ending:'o', isException:false},
  {it:'fratello',  ar:'أخ',        gender:'m', ending:'o', isException:false},
  {it:'negozio',   ar:'متجر',      gender:'m', ending:'o', isException:false},
  {it:'porta',     ar:'باب',       gender:'f', ending:'a', isException:false},
  {it:'casa',      ar:'منزل',      gender:'f', ending:'a', isException:false},
  {it:'scuola',    ar:'مدرسة',     gender:'f', ending:'a', isException:false},
  {it:'macchina',  ar:'سيارة',     gender:'f', ending:'a', isException:false},
  {it:'padre',     ar:'أب',        gender:'m', ending:'e', isException:false},
  {it:'madre',     ar:'أم',        gender:'f', ending:'e', isException:false},
  {it:'nome',      ar:'اسم',       gender:'m', ending:'e', isException:false},
  {it:'voce',      ar:'صوت',       gender:'f', ending:'e', isException:false},
  {it:'radio',     ar:'راديو',     gender:'f', ending:'o', isException:true},
  {it:'mano',      ar:'يد',        gender:'f', ending:'o', isException:true},
  {it:'problema',  ar:'مشكلة',     gender:'m', ending:'a', isException:true},
  {it:'dentista',  ar:'طبيب أسنان',gender:'m', ending:'a', isException:true},
  {it:'estate',      ar:'صيف',                 gender:'f', ending:'e', isException:false},
  {it:'amico',       ar:'صديق',                gender:'m', ending:'o', isException:false},
  {it:'autobus',     ar:'أتوبيس',              gender:'m', ending:'s', isException:true},
  {it:'amica',       ar:'صديقة',               gender:'f', ending:'a', isException:false},
  {it:'cinema',      ar:'سينما',               gender:'m', ending:'a', isException:true},
  {it:'giornale',    ar:'جريدة',               gender:'m', ending:'e', isException:false},
  {it:'pizza',       ar:'بيتزا',               gender:'f', ending:'a', isException:false},
  {it:'cucina',      ar:'مطبخ',                gender:'f', ending:'a', isException:false},
  {it:'camera',      ar:'غرفة',                gender:'f', ending:'a', isException:false},
  {it:'invito',      ar:'دعوة',                gender:'m', ending:'o', isException:false},
  {it:'italiano',    ar:'إيطالي',              gender:'m', ending:'o', isException:false},
  {it:'ufficio',     ar:'مكتب',                gender:'m', ending:'o', isException:false},
  {it:'succo',       ar:'عصير',                gender:'m', ending:'o', isException:false},
  {it:'tempo',       ar:'وقت / طقس',           gender:'m', ending:'o', isException:false},
  {it:'quaderno',    ar:'كراسة',               gender:'m', ending:'o', isException:false},
  {it:'cellulare',   ar:'موبايل',              gender:'m', ending:'e', isException:false},
  {it:'palestra',    ar:'صالة رياضية',         gender:'f', ending:'a', isException:false},
  {it:'bicicletta',  ar:'دراجة هوائية',        gender:'f', ending:'a', isException:false},
  {it:'storia',      ar:'تاريخ / قصة',         gender:'f', ending:'a', isException:false},
  {it:'colazione',   ar:'إفطار',               gender:'f', ending:'e', isException:false},
  {it:'sport',       ar:'رياضة',               gender:'m', ending:'t', isException:true},
  {it:'stadio',      ar:'ملعب',                gender:'m', ending:'o', isException:false},
  {it:'schermo',     ar:'شاشة',                gender:'m', ending:'o', isException:false},
  {it:'spazio',      ar:'فضاء / مساحة',        gender:'m', ending:'o', isException:false},
  {it:'zio',         ar:'عم / خال',            gender:'m', ending:'o', isException:false},
  {it:'zero',        ar:'صفر',                 gender:'m', ending:'o', isException:false},
  {it:'zucchero',    ar:'سكر',                 gender:'m', ending:'o', isException:false},
  {it:'zoo',         ar:'حديقة حيوان',         gender:'m', ending:'o', isException:false},
  {it:'appartamento',ar:'شقة',                 gender:'m', ending:'o', isException:false},
  {it:'ora',         ar:'ساعة / الآن',         gender:'f', ending:'a', isException:false},
  {it:'inverno',     ar:'شتاء',                gender:'m', ending:'o', isException:false},
  {it:'isola',       ar:'جزيرة',               gender:'f', ending:'a', isException:false},
  {it:'esame',       ar:'امتحان',              gender:'m', ending:'e', isException:false},
  {it:'telefono',    ar:'هاتف',                gender:'m', ending:'o', isException:false},
  {it:'tè',          ar:'شاي',                 gender:'m', ending:'è', isException:true},
  {it:'film',        ar:'فيلم',                gender:'m', ending:'m', isException:true},
  {it:'messaggio',   ar:'رسالة',               gender:'m', ending:'o', isException:false},
  {it:'regalo',      ar:'هدية',                gender:'m', ending:'o', isException:false},
  {it:'verità',      ar:'حقيقة',               gender:'f', ending:'à', isException:true},
  {it:'spesa',       ar:'تسوق / مشتريات',      gender:'f', ending:'a', isException:false},
  {it:'lingua',      ar:'لغة / لسان',          gender:'f', ending:'a', isException:false},
  {it:'famiglia',    ar:'عائلة',               gender:'f', ending:'a', isException:false}
];
